### ISSUE TITLE
Missing dependency in `clusterware-sessions`

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/forge-packages#2]
Running `flight session start gnome` spits out the following error:
```
/opt/flight-direct/opt/clusterware/libexec/session/actions/start: line 39: /opt/flight-direct/opt/clusterware/opt/pluginhook/bin/pluginhook: No such file or directory
```

However after running the following, the error disappears:
```
flight forge install pluginhook
```
The `pluginhook` package needs to be added to the list of dependencies.

**Comment by mjtko** [comment]
Possibly this could be made optional (i.e. only used if it's detected) rather than an explicit dependency.

**Comment by mjtko** [comment]
This was fixed in https://github.com/alces-software/forge-packages/commit/c1e450447483c7b5ac65a294b311bcc62fc2b351
