### ISSUE TITLE
Fix hard coded path in `pdsh`

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/forge-packages#3]
There is a path looking for the old clusterware in the `pdsh` module:
```
[root@master ~]# pdsh
pdsh@master: Can't stat "/opt/clusterware/opt/pdsh/lib/pdsh": No such file or directory
pdsh@master: Couldn't load any pdsh modules
```

FlightDirect and Clusterware have been merged into a single directory structure. So it should be:
`/opt/flight-direct/opt/pdsh/lib/pdsh`

**Comment by mjtko** [comment]
This has now caused an issue in the wild.  Could somebody prioritize understanding/fixing it please?

**Comment by WilliamMcCumstie** [comment]
On it
