### ISSUE TITLE
Enable Local Depot by Default in Gridware

### ISSUE THREAD

**Issue by ColonelPanics** [alces-software/forge-packages#8]
On a standard installation of gridware (`flight forge install clusterware-gridware`) it is impossible to install packages or do anything unless the local depot is enabled (`flight gridware depot enable local`) so this should be enabled by default.

I don't see any reason why this would be a bad practice. @mjtko?

**Comment by mjtko** [comment]
Sounds broken to me, default install shouldn't need anything enabling, should already be there.

**Comment by ColonelPanics** [comment]
Fixed and merged into `develop` in ee3b9665ba6064cb59a2f520e2b489477ca8d0a7
